stages:
  data_ingestion:
    cmd: python src/Model/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Model/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/features.pkl 


  prepare_base_model:
    cmd: python src/Model/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Model/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/Model/pipeline/stage_03_training.py
    deps:
      - src/Model/pipeline/stage_03_training.py
      - src/Model/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/features.pkl
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/best_model.keras


  

  evaluation:
    cmd: python src/Model/pipeline/stage_04_evaluation.py
    deps:
      - src/Model/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/features.pkl
      - artifacts/training/best_model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false